use crate::templates::general::CertificateInfo;

#[inline(always)]
pub fn get_certificates<'a>() -> Vec<CertificateInfo<'a>> {
    vec![
        CertificateInfo{
            title: "AI4I® - Literacy in AI",
            issuer: "AI Singapore",
            cred_id: "740716",
            link: "https://learn.aisingapore.org/certificate-verification/815973AF03-7EF3670AC8-132FF3E07/",
            date: "Jul 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/AI4I® - Literacy in AI.webp",
            img_alt: "AI4I® - Literacy in AI Certificate",
        },
        CertificateInfo{
            title: "Google IT Automation with Python Specialization",
            issuer: "Google",
            cred_id: "27YRJV3GHENW",
            link: "https://www.coursera.org/account/accomplishments/specialization/certificate/27YRJV3GHENW",
            date: "Apr 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Google IT Automation with Python Specialization.webp",
            img_alt: "Google IT Automation with Python Specialization Certificate",
        },
        CertificateInfo{
            title: "Automating Real-World Tasks with Python",
            issuer: "Google",
            cred_id: "S3GKRHGQU75D",
            link: "https://www.coursera.org/account/accomplishments/certificate/S3GKRHGQU75D",
            date: "Apr 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Automating Real-World Tasks with Python.webp",
            img_alt: "Automating Real-World Tasks with Python Certificate",
        },
        CertificateInfo{
            title: "Configuration Management and the Cloud",
            issuer: "Google",
            cred_id: "APP8VALHPFNE",
            link: "https://www.coursera.org/account/accomplishments/certificate/APP8VALHPFNE",
            date: "Apr 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Configuration Management and the Cloud.webp",
            img_alt: "Configuration Management and the Cloud Certificate",
        },
        CertificateInfo{
            title: "Troubleshooting and Debugging Techniques",
            issuer: "Google",
            cred_id: "L2RQGZE2NJGL",
            link: "https://www.coursera.org/account/accomplishments/certificate/L2RQGZE2NJGL",
            date: "Mar 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Troubleshooting and Debugging Techniques.webp",
            img_alt: "Troubleshooting and Debugging Techniques Certificate",
        },
        CertificateInfo{
            title: "Introduction to Git and GitHub",
            issuer: "Google",
            cred_id: "BYD5FGYYTUBX",
            link: "https://www.coursera.org/account/accomplishments/certificate/BYD5FGYYTUBX",
            date: "Mar 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Introduction to Git and GitHub.webp",
            img_alt: "Introduction to Git and GitHub Certificate",
        },
        CertificateInfo{
            title: "Using Python to Interact with the Operating System",
            issuer: "Google",
            cred_id: "8HHAFGMBNDA2",
            link: "https://www.coursera.org/account/accomplishments/certificate/8HHAFGMBNDA2",
            date: "Mar 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Using Python to Interact with the Operating System.webp",
            img_alt: "Using Python to Interact with the Operating System Certificate",
        },
        CertificateInfo{
            title: "Crash Course on Python",
            issuer: "Google",
            cred_id: "N7XD22SSPHQV",
            link: "https://www.coursera.org/account/accomplishments/certificate/N7XD22SSPHQV",
            date: "Jan 2023",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/Crash Course on Python.webp",
            img_alt: "Crash Course on Python Certificate",
        },
        CertificateInfo{
            title: "ACA Cloud Computing Certification",
            issuer: "Alibaba Cloud",
            cred_id: "IACA01221000083854L",
            link: "https://xuecdn2.aliyunedu.net/img_8c05d15bb0c25675b6128da24b7fd208.webp",
            date: "Oct 2022",
            expiry: "Oct 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/ACA Cloud Computing Certification.webp",
            img_alt: "ACA Cloud Computing Certification Certificate",
        },
        CertificateInfo{
            title: "Handle Large Traffic with Load Balancer (Exam)",
            issuer: "Alibaba Cloud",
            cred_id: "ACFC06220900083066",
            link: "https://xuecdn2.aliyunedu.net/img_ca4a13bae22d03a114b08fe71831db7f.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Handle Large Traffic with Load Balancer (Exam).webp",
            img_alt: "Handle Large Traffic with Load Balancer (Exam) Certificate",
        },
        CertificateInfo{
            title: "Operate and Manage Object Storage on the Cloud (Exam)",
            issuer: "Alibaba Cloud",
            cred_id: "ACFC05220900083063",
            link: "https://xuecdn2.aliyunedu.net/img_c96af99588cb6d12425ab81663dc366a.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Operate and Manage Object Storage on the Cloud (Exam).webp",
            img_alt: "Operate and Manage Object Storage on the Cloud (Exam) Certificate",
        },
        CertificateInfo{
            title: "Operate and Manage a Cloud Server",
            issuer: "Alibaba Cloud",
            cred_id: "ACLC03220900082979",
            link: "https://xuecdn2.aliyunedu.net/img_77d1a7ef900f46e1fe246ac83734cc99.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Operate and Manage a Cloud Server.webp",
            img_alt: "Operate and Manage a Cloud Server Certificate",
        },
        CertificateInfo{
            title: "Operate and Manage a Cloud Server (Exam)",
            issuer: "Alibaba Cloud",
            cred_id: "ACFC03220900083056",
            link: "https://xuecdn2.aliyunedu.net/img_05b5df2f723123be5b41cf4019a6a119.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Operate and Manage a Cloud Server (Exam).webp",
            img_alt: "Operate and Manage a Cloud Server (Exam) Certificate",
        },
        CertificateInfo{
            title: "Operate and Manage a Relational Database on the Cloud (Exam)",
            issuer: "Alibaba Cloud",
            cred_id: "ACFC04220900083057",
            link: "https://xuecdn2.aliyunedu.net/img_d784d0ca08d9a9acbbe9c57e2e9fdb64.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Operate and Manage a Relational Database on the Cloud (Exam).webp",
            img_alt: "Operate and Manage a Relational Database on the Cloud (Exam) Certificate",
        },
        CertificateInfo{
            title: "Use Cloud Resources Flexibly According to Business Requirement (Exam)",
            issuer: "Alibaba Cloud",
            cred_id: "ACFC13221000083117",
            link: "https://xuecdn2.aliyunedu.net/img_8edea65d96e3e877c81355b9b8771b39.webp",
            date: "Sep 2022",
            expiry: "Sep 2024",
            img_src: "https://storage.kjhjason.com/images/certificates/Use Cloud Resources Flexibly According to Business Requirement (Exam).webp",
            img_alt: "Use Cloud Resources Flexibly According to Business Requirement (Exam) Certificate",
        },
        CertificateInfo{
            title: "TISC 2022 Badge of Participation",
            issuer: "Centre for Strategic Infocomm Technologies (CSIT)",
            cred_id: "6322bfa0f0753f5eed5bff4c",
            link: "https://api.badgr.io/public/assertions/jv-9O1PLT3621wrxTQnizA",
            date: "Sep 2022",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/TISC 2022 Badge of Participation.webp",
            img_alt: "TISC 2022 Badge of Participation Badge",
        },
        CertificateInfo{
            title: "AWS Academy Graduate - AWS Academy Cloud Foundations",
            issuer: "Amazon Web Services Training and Certification",
            cred_id: "f48f6847-73e6-49b9-ae64-df1a86ac7557",
            link: "https://www.credly.com/badges/f48f6847-73e6-49b9-ae64-df1a86ac7557?source=linked_in_profile",
            date: "Jul 2022",
            expiry: "",
            img_src: "https://storage.kjhjason.com/images/certificates/AWS Academy Graduate - AWS Academy Cloud Foundations.webp",
            img_alt: "AWS Academy Graduate - AWS Academy Cloud Foundations Certificate",
        },
    ]
}
